Admin/Controllers/AdminCartController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using RnR.Admin.DbContexts;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using RnR.Admin.Models;
using X.PagedList;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Admin.Controllers
{
    [ApiController]
    public class AdminCartController : Controller
    {
        private MyDbContext dbContext;

        public AdminCartController(MyDbContext context)
        {
            dbContext = context;
        }

        [Authorize]
        [HttpGet, Route("/AdminCart")]
        public async Task<IActionResult> Index(string sortOrder, string searchString, string currentFilter, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.UserIDSortParam = sortOrder == "id" ? "id_desc" : "id";
            ViewBag.UserNameSortParam = sortOrder == "userName" ? "userName_desc" : "userName";
            ViewBag.ProductTitleSortParam = sortOrder == "productTitle" ? "productTitle_desc" : "productTitle";
            ViewBag.BrandSortParam = sortOrder == "brand" ? "brand_desc" : "brand";
            ViewBag.QuantitySortParam = sortOrder == "quantity" ? "quantity_desc" : "quantity";
            ViewBag.PriceSortParam = sortOrder == "price" ? "price_desc" : "price";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;
            ViewBag.UserToken = HttpContext.Session.GetString("Token");

            var cartItems = await (from usr in this.dbContext.Users
                            join crt in this.dbContext.CartItems on usr.userID equals crt.cartID
                            select new CartItemsViewModel()
                            {
                                ID = crt.ID,
                                cartID = crt.cartID,
                                productTitle = crt.productTitle,
                                brand = crt.brand,
                                barcode = crt.barcode,
                                quantity = crt.quantity,
                                price = crt.price,
                                fullUserName = usr.firstName + " " + usr.lastName
                            }).ToListAsync();

            if (!String.IsNullOrEmpty(searchString))
            {
                ViewBag.NoCartItemsFound = null;

                cartItems = await (cartItems.Where(crt => crt.productTitle.Contains(searchString)
                    || crt.brand.Contains(searchString)
                    || crt.fullUserName.Contains(searchString))).ToListAsync();

                if (!cartItems.Any())
                {
                    ViewBag.NoCartItemsFound = "No Cart Items Found";
                }
            }

            switch (sortOrder)
            {
                case "id_desc":
                    cartItems = await (cartItems.OrderByDescending(crt => crt.cartID)).ToListAsync();
                    break;
                case "id":
                    cartItems = await (cartItems.OrderBy(crt => crt.cartID)).ToListAsync();
                    break;
                case "userName_desc":
                    cartItems = await (cartItems.OrderByDescending(crt => crt.fullUserName)).ToListAsync();
                    break;
                case "userName":
                    cartItems = await (cartItems.OrderBy(crt => crt.fullUserName)).ToListAsync();
                    break;
                case "productTitle_desc":
                    cartItems = await (cartItems.OrderByDescending(crt => crt.productTitle)).ToListAsync();
                    break;
                case "productTitle":
                    cartItems = await (cartItems.OrderBy(crt => crt.productTitle)).ToListAsync();
                    break;
                case "brand_desc":
                    cartItems = await (cartItems.OrderByDescending(crt => crt.brand)).ToListAsync();
                    break;
                case "brand":
                    cartItems = await (cartItems.OrderBy(crt => crt.brand)).ToListAsync();
                    break;
                case "quantity_desc":
                    cartItems = await (cartItems.OrderByDescending(crt => crt.quantity)).ToListAsync();
                    break;
                case "quantity":
                    cartItems = await (cartItems.OrderBy(crt => crt.quantity)).ToListAsync();
                    break;
                case "price_desc":
                    cartItems = await (cartItems.OrderByDescending(crt => crt.price)).ToListAsync();
                    break;
                case "price":
                    cartItems = await (cartItems.OrderBy(crt => crt.price)).ToListAsync();
                    break;
                default:
                    break;
            }

            int pageSize = 10;
            int pageNumber = (page ?? 1);

            return View(cartItems.ToPagedList(pageNumber, pageSize));
        }

        [Authorize]
        [HttpGet, Route("/Home/Error")]
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Admin/Views/AdminCart/Index.cshtml
@model X.PagedList.IPagedList<RnR.Admin.Models.CartItemsViewModel>
@using X.PagedList.Mvc.Core;

@{ ViewData["Title"] = "Cart Items"; }

<div class="container" id="page__content" style="display:none;">
    <header class="text-center">
        <h1 class="display-4">@ViewData["Title"]</h1>
    </header>
    <div class="container" style="margin-top: 25px;">
        <div class="row">
            <div class="col-6" style="float:left;">

            </div>
            <div class="col-6" style="float:right;">
                @using (Html.BeginForm("Index", "AdminCart", FormMethod.Get))
                {
                    <p style="margin:5px 0px;float:right;">
                        @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
                        <input style="margin: 5px 0px;" type="submit" value="search" />
                    </p>
                }
            </div>
        </div>
    </div>
    @if (ViewBag.NoCartItemsFound != null)
    {
          <div id="warning__section" class="alert alert-danger" style="text-align:center; margin-top: 10%;">
               <strong>@ViewBag.NoCartItemsFound</strong>
          </div>
    }
    else
    {
        <div class="table-responsive-md">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>@Html.ActionLink("ID", "Index", new { sortOrder = ViewBag.UserIDSortParam, currentFilter = ViewBag.CurrentFilter })</th>
                        <th>@Html.ActionLink("User", "Index", new { sortOrder = ViewBag.UserNameSortParam, currentFilter = ViewBag.CurrentFilter })</th>
                        <th>@Html.ActionLink("Product Title", "Index", new { sortOrder = ViewBag.ProductTitleSortParam, currentFilter = ViewBag.CurrentFilter })</th>
                        <th>@Html.ActionLink("Brand", "Index", new { sortOrder = ViewBag.BrandSortParam, currentFilter = ViewBag.CurrentFilter })</th>
                        <th>@Html.ActionLink("Quantity", "Index", new { sortOrder = ViewBag.QuantitySortParam, currentFilter = ViewBag.CurrentFilter })</th>
                        <th>@Html.ActionLink("Price", "Index", new { sortOrder = ViewBag.PriceSortParam, currentFilter = ViewBag.CurrentFilter })</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var product in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => product.cartID)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => product.fullUserName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => product.productTitle)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => product.brand)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => product.quantity)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => product.price)
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
            <div class="container">
                <div style="float:right;">
                    @Html.PagedListPager(Model, page => Url.Action("Index",
                        new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }),
                        new X.PagedList.Web.Common.PagedListRenderOptions
                        {
                            DisplayLinkToIndividualPages = true,
                            LiElementClasses = new string[] { "page-item" },
                            PageClasses = new string[] { "page-link" }
                        })
                </div>
            </div>
        </div>
    }
</div>


@await Html.PartialAsync("/Views/PartialViews/Spinner.cshtml")