Admin/Controllers/AdminProductsController.cs
using System;
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using RnR.Admin.Models;
using RnR.Admin.Entities;
using RnR.Admin.DbContexts;
using System.Linq;
using X.PagedList;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;

namespace RnR.Admin.Controllers
{
    [ApiController]
    public class AdminProductsController : Controller
    {
        private MyDbContext dbContext;

        public AdminProductsController(MyDbContext context)
        {
            dbContext = context;
        }

        [Authorize]
        [HttpGet, Route("/AdminProducts")]
        public async Task<IActionResult> Index(string sortOrder, string searchString, string currentFilter, int? page)
        {
            ViewBag.UserToken = HttpContext.Session.GetString("Token");
            ViewBag.CurrentSort = sortOrder;
            ViewBag.IDSortParam = sortOrder == "id" ? "id_desc" : "id";
            ViewBag.TitleSortParam = sortOrder == "title" ? "title_desc" : "title";
            ViewBag.BrandSortParam = sortOrder == "brand" ? "brand_desc" : "brand";
            ViewBag.CategorySortParam = sortOrder == "category" ? "category_desc" : "category";
            ViewBag.QuantitySortParam = sortOrder == "quantity" ? "quantity_desc" : "quantity";
            ViewBag.PriceSortParam = sortOrder == "price" ? "price_desc" : "price";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            var products = await (from prod in this.dbContext.Products
                           select prod).ToListAsync();

            if (!String.IsNullOrEmpty(searchString))
            {
                ViewBag.NoProductsFound = null;

                products = await (products.Where(product => product.title.Contains(searchString)
                    || product.brand.Contains(searchString)
                    || product.barcode.Contains(searchString)
                    || product.category.Contains(searchString)
                    || product.quantity.Contains(searchString))).ToListAsync();

                if (!products.Any())
                {
                    ViewBag.NoProductsFound = "No products found";
                }
            }

            switch (sortOrder)
            {
                case "id_desc":
                    products = await (products.OrderByDescending(product => product.productID)).ToListAsync();
                    break;
                case "id":
                    products = await (products.OrderBy(product => product.productID)).ToListAsync();
                    break;
                case "title_desc":
                    products = await (products.OrderByDescending(product => product.title)).ToListAsync();
                    break;
                case "title":
                    products = await (products.OrderBy(product => product.title)).ToListAsync();
                    break;
                case "brand_desc":
                    products = await (products.OrderByDescending(product => product.brand)).ToListAsync();
                    break;
                case "brand":
                    products = await (products.OrderBy(product => product.brand)).ToListAsync();
                    break;
                case "category_desc":
                    products = await (products.OrderByDescending(product => product.category)).ToListAsync();
                    break;
                case "category":
                    products = await (products.OrderBy(product => product.category)).ToListAsync();
                    break;
                case "quantity_desc":
                    products = await (products.OrderByDescending(product => product.quantity)).ToListAsync();
                    break;
                case "quantity":
                    products = await (products.OrderBy(product => product.quantity)).ToListAsync();
                    break;
                case "price_desc":
                    products = await (products.OrderByDescending(product => product.price)).ToListAsync();
                    break;
                case "price":
                    products = await (products.OrderBy(product => product.price)).ToListAsync();
                    break;
            }

            int pageSize = 10;
            int pageNumber = (page ?? 1);

            return View(products.ToPagedList(pageNumber, pageSize));
        }

        [Authorize]
        [HttpGet, Route("/CreateProduct")]
        public async Task<IActionResult> CreateProduct()
        {
            ViewBag.UserToken = HttpContext.Session.GetString("Token");

            ViewBag.Brands = await (from prd in this.dbContext.Products
                             select new Product()
                             { brand = prd.brand }).Distinct().OrderBy(b => b.brand).ToListAsync();

            ViewBag.Categories = await (from prd in this.dbContext.Products
                                 select new Product()
                                 { category = prd.category }).Distinct().OrderBy(c => c.category).ToListAsync();

            return View();
        }

        [Authorize]
        [HttpPost, Route("/CreateProduct")]
        public async Task<IActionResult> CreateProduct([FromForm] Product product)
        {
            ViewBag.UserToken = HttpContext.Session.GetString("Token");


            Product newProduct = new Product()
            {
                title = product.title,
                category = product.category,
                brand = product.brand,
                uri = product.uri,
                price = product.price,
                descr = product.descr,
                features = product.features,
                _usage = product._usage,
                quantity = product.quantity,
                barcode = product.barcode
            };

            try
            {
                await this.dbContext.Products.AddAsync(newProduct);
                await this.dbContext.SaveChangesAsync();
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
                throw new Exception(ex.InnerException.ToString());
            }

            return RedirectToAction("Index", "AdminLanding");
        }

        [Authorize]
        [HttpGet, Route("/EditProduct")]
        public async Task<IActionResult> EditProduct(string barcode, int productID)
        {
            ViewBag.UserToken = HttpContext.Session.GetString("Token");

            var products = from prod in this.dbContext.Products
                           select prod;

            Product product = await products
                .Where(p => p.barcode == barcode && p.productID == productID)
                .FirstOrDefaultAsync();

            return View(product);
        }

        [Authorize]
        [HttpPost, Route("/EditProduct")]
        public async Task<IActionResult> EditProduct([FromForm] Product product)
        {
            ViewBag.UserToken = HttpContext.Session.GetString("Token");

            var currentProduct = await (from prd in this.dbContext.Products
                                 where prd.productID == product.productID
                                 select prd).SingleOrDefaultAsync();

            try
            {
                if (currentProduct != null)
                {
                    currentProduct.title = product.title;
                    currentProduct.barcode = product.barcode;
                    currentProduct.category = product.category;
                    currentProduct.brand = product.brand;
                    currentProduct.productID = product.productID;
                    currentProduct.descr = product.descr;
                    currentProduct.price = product.price;
                    currentProduct.quantity = product.quantity;
                    currentProduct.features = product.features;
                    currentProduct.uri = product.uri;
                    currentProduct._usage = product._usage;

                    await this.dbContext.SaveChangesAsync();
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
                throw new Exception(ex.InnerException.ToString());
            }

            return RedirectToAction("Index");
        }

        [Authorize]
        [HttpGet, Route("/ProductDetails")]
        public async Task<IActionResult> ProductDetails(string barcode, int productID)
        {
            ViewBag.UserToken = HttpContext.Session.GetString("Token");

            var products = await (from prod in this.dbContext.Products
                           select prod).ToListAsync();

            Product product = products
                .Where(p => p.barcode == barcode && p.productID == productID)
                .FirstOrDefault();

            return View(product);
        }

        [Authorize]
        [HttpGet, Route("/DeleteProduct")]
        public async Task<IActionResult> DeleteProduct(string barcode, int productID)
        {
            var currentProduct = await(from prd in this.dbContext.Products
                                 where prd.productID == productID && prd.barcode == barcode
                                 select prd).FirstOrDefaultAsync();

            try
            {
                this.dbContext.Remove(currentProduct);
                await this.dbContext.SaveChangesAsync();

            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
                throw new Exception(ex.InnerException.ToString());
            }

            return RedirectToAction("Index", "AdminLanding");
        }

        [Authorize]
        [HttpGet, Route("/Home/Error")]
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]

Admin/Views/AdminProducts/CreateProduct.cshtml
@model RnR.Admin.Entities.Product

@{ ViewData["Title"] = "Create Product"; }

<div class="container" id="page__content" style="display:none;">
    <header class="text-center">
        <h4 class="display-4">@ViewData["Title"]</h4>
    </header>
    <div class="container-fluid">
        <div style="margin-top: 35px;">
            <div>
                <form style="text-align:left;margin-top:1.5rem;" method="post" asp-controller="AdminProducts" asp-action="CreateProduct" class="form-vertical" role="form" autocomplete="off">
                    <div class="row g-3">
                        <div class="col"></div>
                        <div class="col-sm-4">
                            <div class="input__group">
                                <label class="form-label" asp-for="title">@Html.Label("Product Title: ")</label>
                                <input type="text" asp-for="title" class="form-control" placeholder="" required />
                                <div class="invalid-feedback">
                                    A valid product title is requires
                                </div>
                            </div>
                            <div class="input__group">
                                <label class="form-label" asp-for="category" style="margin-top:1rem;">@Html.Label("Category: ")</label>
                                <select class="form-control" asp-for="category" required>
                                    @foreach (var item in ViewBag.Categories)
                                    {
                                        <option>@item.category</option>
                                    }
                                </select>
                                <div class="invalid-feedback">
                                    A valid category is required
                                </div>
                            </div>
                            <div class="input__group">
                                <label class="form-label" asp-for="brand" style="margin-top:1rem;">@Html.Label("Brand: ")</label>
                                <select class="form-control" asp-for="brand" required>
                                    @foreach (var item in ViewBag.Brands)
                                    {
                                         <option>@item.brand</option>
                                    }
                                </select>
                                <div class="invalid-feedback">
                                    A valid brand is required
                                </div>
                            </div>
                            <div class="input__group">
                                <label class="form-label" asp-for="barcode" style="margin-top:1rem;">@Html.Label("Barcode: ")</label>
                                <input type="text" asp-for="barcode" class="form-control" placeholder="" required />
                                <div class="invalid-feedback">
                                    A valid barcode is required
                                </div>
                            </div>
                            <div class="input__group">
                                <label class="form-label" asp-for="_usage" style="margin-top:1rem;">@Html.Label("Usage: ")</label>
                                <textarea class="form-control" asp-for="_usage" rows="3" required></textarea>
                                <div class="invalid-feedback">
                                    A valid product usage is required
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div class="input__group">
                                <label class="form-label" asp-for="quantity">@Html.Label("Quantity: ")</label>
                                <input type="text" asp-for="quantity" class="form-control" placeholder="" required />
                                <div class="invalid-feedback">
                                    A valid product quantity is required
                                </div>
                            </div>
                            <div class="input__group">
                                <label class="form-label" asp-for="features" style="margin-top:1rem;">@Html.Label("Features: ")</label>
                                <input type="text" asp-for="features" class="form-control" placeholder="" required />
                                <div class="invalid-feedback">
                                    A valid product feature is required
                                </div>
                            </div>
                            <div class="input__group">
                                <label class="form-label" asp-for="price" style="margin-top:1rem;">@Html.Label("Price: ")</label>
                                <input type="number" asp-for="price" class="form-control" placeholder="" required />
                                <div class="invalid-feedback">
                                    A valid product price is required
                                </div>
                            </div>
                            <div class="input__group">
                                <label class="form-label" asp-for="uri" style="margin-top:1rem;">@Html.Label("URI: ")</label>
                                <input type="text" asp-for="uri" class="form-control" placeholder="" required />
                                <div class="invalid-feedback">
                                    A valid product image URI is required
                                </div>
                            </div>
                            <div class="input__group">
                                <label class="form-label" asp-for="descr" style="margin-top:1rem;">@Html.Label("Description: ")</label>
                                <textarea class="form-control" asp-for="descr" rows="3" required></textarea>
                                <div class="invalid-feedback">
                                    A valid product description is required
                                </div>
                            </div>
                        </div>
                        <div class="col"></div>
                    </div>
                    <div style="text-align:center;margin-top:3rem;padding-top:1rem;">
                        <div class="container">
                            <div class="row">
                                <div class="col-md-12 col-sm-6">
                                    <input class="btn btn-primary" type="submit" value="Create Product" />
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@await Html.PartialAsync("/Views/PartialViews/Spinner.cshtml")

Admin/Views/AdminProducts/EditProduct.cshtml
@model RnR.Admin.Entities.Product

@{ ViewData["Title"] = "Edit Product"; }

<div id="page__content" style="display:none;">
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-md-12">
                <header class="text-center">
                    <h4 class="display-4">@ViewData["Title"]</h4>
                </header>
            </div>
        </div>
    </div>

    <div class="container-fluid" style="margin-top: 25px;">
        <form method="post" novalidate asp-controller="AdminProducts" asp-action="EditProduct" class="form-vertical needs-validation" role="form" autocomplete="off">
            @Html.HiddenFor(model => model.productID)
            <div class="row g-3">
                <div class="col"></div>
                <div class="col-sm-4">
                    <div class="input__group">
                        <label class="form-label" asp-for="title">@Html.Label("Product Title: ")</label>
                        <input type="text" asp-for="title" class="form-control" placeholder="" value="@Model.title" required />
                        <div class="invalid-feedback">
                            A valid product title is requires
                        </div>
                    </div>
                    <div class="input__group">
                        <label class="form-label" asp-for="category" style="margin-top:1rem;">@Html.Label("Category: ")</label>
                        <input type="text" asp-for="category" class="form-control" placeholder="" value="@Model.category" required />
                        <div class="invalid-feedback">
                            A valid category is required
                        </div>
                    </div>
                    <div class="input__group">
                        <label class="form-label" asp-for="brand" style="margin-top:1rem;">@Html.Label("Brand: ")</label>
                        <input type="text" asp-for="brand" class="form-control" placeholder="" value="@Model.brand" required />
                        <div class="invalid-feedback">
                            A valid brand is required
                        </div>
                    </div>
                    <div class="input__group">
                        <label class="form-label" asp-for="barcode" style="margin-top:1rem;">@Html.Label("Barcode: ")</label>
                        <input type="text" asp-for="barcode" class="form-control" placeholder="" value="@Model.barcode" required />
                        <div class="invalid-feedback">
                            A valid barcode is required
                        </div>
                    </div>
                    <div class="input__group">
                        <label class="form-label" asp-for="_usage" style="margin-top:1rem;">@Html.Label("Usage: ")</label>
                        <textarea class="form-control" asp-for="_usage" rows="3" required>@Model._usage</textarea>
                        <div class="invalid-feedback">
                            A valid product usage is required
                        </div>
                    </div>
                </div>
                <div class="col-sm-4">
                    <div class="input__group">
                        <label class="form-label" asp-for="quantity">@Html.Label("Quantity: ")</label>
                        <input type="text" asp-for="quantity" class="form-control" placeholder="" value="@Model.quantity" required />
                        <div class="invalid-feedback">
                            A valid product quantity is required
                        </div>
                    </div>
                    <div class="input__group">
                        <label class="form-label" asp-for="features" style="margin-top:1rem;">@Html.Label("Features: ")</label>
                        <input type="text" asp-for="features" class="form-control" placeholder="" value="@Model.features" required />
                        <div class="invalid-feedback">
                            A valid product feature is required
                        </div>
                    </div>
                    <div class="input__group">
                        <label class="form-label" asp-for="price" style="margin-top:1rem;">@Html.Label("Price: ")</label>
                        <input type="number" asp-for="price" class="form-control" placeholder="" value="@Model.price" required />
                        <div class="invalid-feedback">
                            A valid product price is required
                        </div>
                    </div>
                    <div class="input__group">
                        <label class="form-label" asp-for="uri" style="margin-top:1rem;">@Html.Label("URI: ")</label>
                        <input type="text" asp-for="uri" class="form-control" placeholder="" value="@Model.uri" required />
                        <div class="invalid-feedback">
                            A valid product image URI is required
                        </div>
                    </div>
                    <div class="input__group">
                        <label class="form-label" asp-for="descr" style="margin-top:1rem;">@Html.Label("Description: ")</label>
                        <textarea class="form-control" asp-for="descr" rows="3" required>@Model.descr</textarea>
                        <div class="invalid-feedback">
                            A valid product description is required
                        </div>
                    </div>
                </div>
                <div class="col"></div>
            </div>
            <div style="text-align:center;margin-top:3rem;padding-top:1rem;">
                <div class="container">
                    <div class="row">
                        <div class="col-md-12 col-sm-6">
                            <input class="btn btn-primary" type="submit" value="Update Product" />
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

@await Html.PartialAsync("/Views/PartialViews/Spinner.cshtml")

Admin/Views/AdminProducts/Index.cshtml
@model X.PagedList.IPagedList<RnR.Admin.Entities.Product>
@using X.PagedList.Mvc.Core;

<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{ ViewData["Title"] = "Products"; }

<div id="page__content" style="display:none;">
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-md-12">
                <header class="text-center">
                    <h4 class="display-4">@ViewData["Title"]</h4>
                </header>
            </div>
        </div>
    </div>
    <div class="container" style="margin-top:25px">
        <div class="row">
             <div class="col-6" style="float:left;">
                <p style="margin: 5px 0px;">
                    @Html.ActionLink("Create Product", "CreateProduct")
                </p>
            </div>
            <div class="col-6" style="float:right;">
                @using (Html.BeginForm("Index", "AdminProducts", FormMethod.Get))
                {
                    <p style="margin: 5px 0px; float:right;">
                        @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
                        <input style="margin: 5px 0px;" type="submit" value="Search" />
                    </p>
                }
            </div>
        </div>
    </div>
    <div class="container">
        @if (ViewBag.NoProductsFound == null)
        {
            <div class="row table-responsive-md" style="margin-top: 10px;">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>@Html.ActionLink("ID", "Index", new { sortOrder = ViewBag.IDSortParam, currentFilter = ViewBag.CurrentFilter })</th>
                            <th>@Html.ActionLink("Title", "Index", new { sortOrder = ViewBag.TitleSortParam, currentFilter = ViewBag.CurrentFilter })</th>
                            <th>@Html.ActionLink("Category", "Index", new { sortOrder = ViewBag.CategorySortParam, currentFilter = ViewBag.CurrentFilter })</th>
                            <th>@Html.ActionLink("Brand", "Index", new { sortOrder = ViewBag.BrandSortParam, currentFilter = ViewBag.CurrentFilter })</th>
                            <th>@Html.ActionLink("Quantity", "Index", new { sortOrder = ViewBag.QuantitySortParam, currentFilter = ViewBag.CurrentFilter })</th>
                            <th>@Html.ActionLink("Price", "Index", new { sortOrder = ViewBag.PriceSortParam, currentFilter = ViewBag.CurrentFilter })</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var product in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => product.productID)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => product.title)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => product.category)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => product.brand)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => product.quantity)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => product.price)
                                </td>
                                <td>
                                    @Html.ActionLink("Edit", "EditProduct", new { barcode = product.barcode, productID = product.productID }) |
                                    @Html.ActionLink("Details", "ProductDetails", new { barcode = product.barcode, productID = product.productID }) |
                                    @Html.ActionLink("Delete", "DeleteProduct", new { barcode = product.barcode, productID = product.productID }) 
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
                <div class="container" style="float:right;">
                    <div style="float:right;">
                        @Html.PagedListPager(Model, page => Url.Action("Index",
                            new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }),
                            new X.PagedList.Web.Common.PagedListRenderOptions
                            {
                                DisplayLinkToIndividualPages = true,
                                LiElementClasses = new string[] { "page-item" },
                                PageClasses = new string[] { "page-link" }
                            })
                    </div>
                </div>
            </div>
         }
         else
         {
            <div id="warning__section" class="alert alert-danger" style="text-align:center; margin-top: 10%;">
                <strong>@ViewBag.NoProductsFound</strong>
            </div>
         }
    </div>
</div>

@await Html.PartialAsync("/Views/PartialViews/Spinner.cshtml")

Admin/Views/AdminProducts/ProductDetails.cshtml
@model RnR.Admin.Entities.Product

@{ ViewData["Title"] = "Details"; }

<div class="container" id="page__content" style="display:none;">
    <div style="margin-top: 5%;">
        <header class="text-left">
            <h4 class="display-4">@ViewData["Title"]</h4>
        </header>
    </div>
    <div class="table-responsive-md" style="margin-top:2%;">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Barcode</th>
                    <th>Title</th>
                    <th>Category</th>
                    <th>Brand</th>
                    <th>Quantity</th>
                    <th>Price</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => Model.productID)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => Model.barcode)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => Model.title)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => Model.category)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => Model.brand)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => Model.quantity)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => Model.price)
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>

@await Html.PartialAsync("/Views/PartialViews/Spinner.cshtml")