Admin/Controllers/AdminLoginController.cs
using System;
using System.Diagnostics;
using System.Linq;
using RnR.Admin.DbContexts;
using RnR.Admin.Models;
using Microsoft.AspNetCore.Mvc;
using RnR.Admin.Entities;
using RnR.Services.HashingService;
using Microsoft.AspNetCore.Authorization;
using Microsoft.Extensions.Configuration;
using RnR.Admin.Repositories;
using RnR.Security.TokenServices;
using Microsoft.AspNetCore.Http;
using RnR.Security.Models;
using RnR.Data.Logger;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Admin.Controllers
{
    [ApiController]
    public class AdminLoginController : Controller
    {
        private MyDbContext dbContext;
        private readonly IConfiguration config;
        private readonly IUserRepository userRepo;
        private readonly ITokenService tokenService;
        private string generatedToken;
        private LogService logService;

        public AdminLoginController(MyDbContext _context, IConfiguration _config, IUserRepository _userRepo, ITokenService _tokenService)
        {
            dbContext = _context;
            config = _config;
            userRepo = _userRepo;
            tokenService = _tokenService;
            logService = new LogService();
        }

        [AllowAnonymous]
        [HttpGet, Route("/Login")]
        public IActionResult Login()
        {
            return View();
        }

        [AllowAnonymous]
        [HttpPost, Route("/Login")]
        public IActionResult Login([FromForm] LoginModel model)
        {
            var encPassword = UserHasherService.encrypt(model.password);

            var query = from usr in this.dbContext.Users
                        where usr.encPassword == encPassword
                            && usr.email == model.email
                            && usr.userRole == "Admin"
                        select usr;

            if (query.Count() <= 0)
            {
                ViewBag.FailedLogin = "Unable to login, please try again";
                logService.AdminLogWrite("Error:", string.Format("Unable to login user {0}", arg0: model.email));
                return View(model);
            }
            else
            {
                var user = query.FirstOrDefault<User>();

                LoginDTOModel validUser = new LoginDTOModel()
                {
                    email = user.email,
                    password = user.encPassword,
                    role = user.userRole
                };

                if (validUser.role == "Admin" && validUser.email == model.email)
                {
                    generatedToken = tokenService.BuildToken(config["Jwt:Key"].ToString(),
                        config["Jwt:Issuer"].ToString(),
                        config["Jwt:Audience"].ToString(),
                        validUser);

                    HttpContext.Session.SetString("Token", generatedToken);
                    HttpContext.Session.SetString("UserName", user.firstName);
                    HttpContext.Session.SetString("UserEmail", user.email);
                    logService.AdminLogWrite("Info:", string.Format("Administrator: {0} Logged In...", arg0: validUser.email));

                    return Redirect("/AdminLanding/Index");
                }
                else
                {
                    ViewBag.FailedLogin = "Unable to login, please try again";
                    return View(model);
                }
            }
        }
        
        [HttpGet, Route("/Home/Error")]
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Admin/Views/AdminLogin/Login.cshtml
@model RnR.Security.Models.LoginModel

@{ ViewData["Title"] = "Admin Login"; }

<div class="container">
    <div class="row">
        <div class="col-xs-12 col-md-12 col-sm-6">
            <header class="text-center" style="margin-top: 5%;">
                <h4 class="display-4">@ViewData["Title"]</h4>
            </header>
        </div>
    </div>
</div>
<div class="container">
    <div class="row" style="margin-top:15%">
        <div class="col">

        </div>
        <div class="col-md-4 col-sm-12">
            <form method="post" asp-controller="AdminLogin" asp-action="Login" class="form-horizontal" role="form" autocomplete="off">
                <div class="mb-3">
                    <label for="email" class="form-label" style="font-size: 1.2rem;">Email Address</label>
                    <input type="email" style="font-size: 1rem;" class="form-control" asp-for="email" required />
                </div>
                <div class="mb-3">
                    <label for="password" class="form-label" style="font-size: 1.2rem;">Password</label>
                    <input type="password" style="font-size: 1rem;" class="form-control" asp-for="password" required />
                </div>
                <button style="margin-left: 38%; margin-top: 2.5rem;" type="submit" class="btn btn-primary">Login</button>
            </form>
            @if (ViewBag.FailedLogin != null)
            {
                <div class="alert alert-danger" style="text-align: center; margin-top: 6%; font-size: 1.2rem;">
                    <strong>@ViewBag.FailedLogin</strong>
                </div>
            }
        </div>
        <div class="col">

        </div>
    </div>
</div>