Admin/Controllers/AdminUsersController.cs
using System;
using System.Diagnostics;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using RnR.Admin.Models;
using RnR.Admin.Entities;
using RnR.Admin.DbContexts;
using X.PagedList;
using RnR.Services.HashingService;
using Microsoft.AspNetCore.Http;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;

namespace RnR.Admin.Controllers
{
    [ApiController]
    public class AdminUsersController : Controller
    {
        private MyDbContext dbContext;
        private UserService userService;

        public AdminUsersController(MyDbContext context)
        {
            dbContext = context;
            userService = new UserService(dbContext);
        }

        [Authorize]
        [HttpGet, Route("/AdminUsers")]
        public async Task<IActionResult> Index(string sortOrder, string searchString, string currentFilter, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParam = sortOrder == "name" ? "name_desc" : "name";
            ViewBag.UserRoleSortParam = sortOrder == "userRole" ? "userRole_desc" : "userRole";
            ViewBag.LastNameSortParam = sortOrder == "lastName" ? "lastName_desc" : "lastName";
            ViewBag.EmailSortParam = sortOrder == "email" ? "email_desc" : "email";
            ViewBag.DateSortParam = sortOrder == "date" ? "date_desc" : "date";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;
            ViewBag.UserToken = HttpContext.Session.GetString("Token");

            var users = await (from usr in this.dbContext.Users
                        select usr).ToListAsync();

            if (!String.IsNullOrEmpty(searchString))
            {
                ViewBag.NoUsersFound = null;

                users = await (users.Where(usr => usr.lastName.Contains(searchString)
                    || usr.firstName.Contains(searchString)
                    || usr.email.Contains(searchString))).ToListAsync();

                if (!users.Any())
                {
                    ViewBag.NoUsersFound = "No users found";
                }
            }

            switch (sortOrder)
            {
                case "userRole_desc":
                    users = await (users.OrderByDescending(user => user.userRole)).ToListAsync();
                    break;
                case "userRole":
                    users = await (users.OrderBy(user => user.userRole)).ToListAsync();
                    break;
                case "name":
                    users = await (users.OrderBy(user => user.firstName)).ToListAsync();
                    break;
                case "name_desc":
                    users = await (users.OrderByDescending(user => user.firstName)).ToListAsync();
                    break;
                case "lastName":
                    users = await (users.OrderBy(user => user.lastName)).ToListAsync(); ;
                    break;
                case "lastName_desc":
                    users = await (users.OrderByDescending(user => user.lastName)).ToListAsync();
                    break;
                case "email":
                    users = await (users.OrderBy(user => user.email)).ToListAsync(); ;
                    break;
                case "email_desc":
                    users = await (users.OrderByDescending(user => user.email)).ToListAsync();
                    break;
                case "date":
                    users = await (users.OrderBy(user => user.doj)).ToListAsync(); ;
                    break;
                case "date_desc":
                    users = await (users.OrderByDescending(user => user.doj)).ToListAsync();
                    break;
                default:
                    users = await (users.OrderBy(user => user.lastName)).ToListAsync();
                    break;
            }

            int pageSize = 5;
            int pageNumber = (page ?? 1);

            return View(users.ToPagedList(pageNumber, pageSize));
        }

        [Authorize]
        [HttpGet, Route("/Details")]
        public async Task<IActionResult> Details(int userID, string email)
        {
            ViewBag.UserToken = HttpContext.Session.Get("Token");
            ViewBag.HasCartItems = null;
            ViewBag.HasPaidForItems = null;
            ViewBag.HasShoppingLists = null;
            ViewBag.HasFavorites = null;

            var user = await userService.getUser(userID, email);
            var cartItems = await userService.getCartItems(userID);
            var paidItems = await userService.getPaidItems(userID);
            var shoppingLists = await userService.getShoppingLists(userID);
            var favoriteItems = await userService.getFavoriteItems(userID);

            UserDetailsViewModel model = new UserDetailsViewModel()
            {
                firstName = user.firstName,
                lastName = user.lastName,
                email = user.email,
                userRole = user.userRole,
                doj = user.doj.ToShortDateString(),
                cartItems = new List<CartItems>(),
                paidForItems = new List<PaidForItems>(),
                shoppingLists = new List<ShoppingLists>(),
                favoriteItems = new List<FavoriteItems>()
            };

            if (cartItems.Any())
            {
                ViewBag.HasCartItems = true;

                foreach (var item in cartItems)
                {
                    model.cartItems.Add(new CartItems()
                    {
                        productTitle = item.productTitle,
                        brand = item.brand,
                        price = item.price,
                        quantity = item.quantity,
                        barcode = item.barcode
                    });
                }
            }

            if (paidItems.Any())
            {
                ViewBag.HasPaidForItems = true;

                foreach (var item in paidItems)
                {
                    model.paidForItems.Add(new PaidForItems()
                    {
                        productTitle = item.productTitle,
                        brand = item.brand,
                        price = item.price,
                        quantity = item.quantity,
                        barcode = item.barcode
                    });
                }
            }

            if (shoppingLists.Any())
            {
                ViewBag.HasShoppingLists = true;

                foreach (var list in shoppingLists)
                {
                    model.shoppingLists.Add(new ShoppingLists()
                    {
                        listName = list.listName,
                        userListID = list.ID
                    });
                }
            }

            if (favoriteItems.Any())
            {
                ViewBag.HasFavorites = true;

                foreach (var item in favoriteItems)
                {
                    model.favoriteItems.Add(new FavoriteItems()
                    {
                        favID = item.favID,
                        productTitle = item.productTitle,
                        brand = item.brand,
                        barcode = item.barcode,
                        price = item.price
                    });
                }
            }

            return View(model);
        }

        [Authorize]
        [HttpGet, Route("/Create")]
        public IActionResult Create()
        {
            ViewBag.UserToken = HttpContext.Session.GetString("Token");
            return View();
        }

        [Authorize]
        [HttpPost, Route("/Create")]
        public async Task<IActionResult> Create([FromForm] User user)
        {
            ViewBag.UserToken = HttpContext.Session.GetString("Token");

            string _encPassword = UserHasherService.encrypt(user.encPassword);

            var emailExists = await (from usr in this.dbContext.Users
                              where usr.email == user.email
                              select usr).ToListAsync();

            if (emailExists.Count() > 0)
            {
                ViewBag.ErrorMessage = "Email already exists, please use a different address";

                return View(user);
            }
            else
            {
                User _user = new User()
                {
                    firstName = user.firstName,
                    lastName = user.lastName,
                    email = user.email,
                    doj = DateTime.Now.ToLocalTime(),
                    encPassword = _encPassword,
                    userRole = user.userRole
                };

                try
                {
                    await dbContext.Users.AddAsync(_user);
                    await dbContext.SaveChangesAsync();
                    ViewBag.ErrorMessage = null;
                }
                catch (Exception e)
                {
                    Console.WriteLine(e.Message);
                    throw new Exception(e.InnerException.ToString());
                }

                return RedirectToAction("Index");
            }
        }

        [Authorize]
        [HttpGet, Route("/Edit")]
        public async Task<IActionResult> Edit(int userID, string email)
        {
            ViewBag.UserToken = HttpContext.Session.GetString("Token");

            var currentDetails = await userService.getUser(userID, email);

            return View(currentDetails);
        }

        [Authorize]
        [HttpPost, Route("/Edit")]
        public async Task<IActionResult> Edit([FromForm] User user)
        {
            var currentUser = await this.dbContext.Users
                .SingleOrDefaultAsync(u => u.userID == user.userID
                    && u.email == user.email

Admin/Views/AdminUsers/Create.cshtml
@model RnR.Admin.Entities.User

@{ ViewData["Title"] = "Create User"; }

<div class="container" id="page__content" style="display:none;">
    <header class="text-center">
        <h4 class="display-4">@ViewData["Title"]</h4>
    </header>
    <div class="container" style="margin-top:35px;">
        <div class="row">
            <div class="col">

            </div>
            <div class="col-6" style="width: 100%;">
                @if (ViewBag.ErrorMessage != null)
                {
                    <div class="alert alert-danger">
                        <strong>@ViewBag.ErrorMessage</strong>
                    </div>
                }
                <form style="text-align:center;margin-top:1.5rem;" method="post" asp-controller="AdminUsers" asp-action="Create" class="form-vertical needs-validation" role="form" autocomplete="off">
                    <table style="margin-left:1rem;">
                        <tr>
                            <td><label class="control-label" style="float:left;vertical-align:bottom">@Html.Label("Role: ")</label></td>
                            <td>
                                <select class="form-control" name="userRole" id="userRole" style="margin: 10px 50px;" required>
                                    <option value="">Select User Role</option>
                                    <option value="User">User</option>
                                    <option value="Admin">Admin</option>
                                </select>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <label class="control-label" style="float:left;vertical-align:bottom;">@Html.Label("Name: ")</label>
                            </td>
                            <td>
                                <input class="form-control" style="margin: 10px 50px;" asp-for="firstName" type="text" required />
                            </td>
                        </tr>
                        <tr>
                            <td><label class="control-label" style="float:left;vertical-align:bottom;">@Html.Label("Surname: ")</label></td>
                            <td>
                                <input class="form-control" style="margin: 10px 50px;" asp-for="lastName" type="text" required />
                            </td>
                        </tr>
                        <tr>
                            <td><label class="control-label" style="float:left;vertical-align:bottom;">@Html.Label("Email: ")</label></td>
                            <td>
                                <input class="form-control" style="margin: 10px 50px;" asp-for="email" type="email" autocomplete="off" required />
                            </td>
                        </tr>
                        <tr>
                            <td><label class="control-label" style="float:left;vertical-align:bottom;">@Html.Label("Password: ")</label></td>
                            <td>
                                <input class="form-control" style="margin: 10px 50px;" asp-for="encPassword" type="password" autocomplete="off" required />
                            </td>
                        </tr>
                    </table>
                    <input style="margin-top: 25px;" class="btn btn-primary" type="submit" value="Create User" />
                </form>
            </div>
            <div class="col">

            </div>
        </div>
    </div>
</div>

@await Html.PartialAsync("/Views/PartialViews/Spinner.cshtml")

Admin/Views/AdminUsers/Details.cshtml
@model RnR.Admin.Models.UserDetailsViewModel

@{
   ViewData["Details"] = "Details";
   ViewData["CartItems"] = "Cart Items";
   ViewData["NoCartItems"] = "User Has No Cart Items";
   ViewData["PaidItems"] = "Paid Items";
   ViewData["ShoppingLists"] = "Shopping Lists";
   ViewData["FavoriteItems"] = "Favorites";
}

<div class="container" id="page__content" style="display:none;">
    <div style="margin-top:5%;">
        <header class="text-left">
            <h4 class="display-4">@ViewData["Details"]</h4>
        </header>
    </div>
    <div class="table-responsive-md" style="margin-top: 2%;">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>User Role</th>
                    <th>Name</th>
                    <th>Surname</th>
                    <th>Email</th>
                    <th>Date Joined</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => Model.userRole)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => Model.firstName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => Model.lastName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => Model.email)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => Model.doj)
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
    <div style="margin-top:5%;">
        <header class="text-left">
            <h6 class="display-4">@ViewData["CartItems"]</h6>
        </header>
    </div>
    @if (ViewBag.HasCartItems != null)
    {
        <div class="table-responsive-md" style="margin-top: 2%;">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Barcode</th>
                        <th>Title</th>
                        <th>Brand</th>
                        <th>Quantity</th>
                        <th>Price</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.cartItems)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.barcode)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.productTitle)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.brand)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.quantity)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.price)
                            </td>
                        </tr>
                      }
                </tbody>
            </table>
        </div>
     }
     else
     {
         <div class="alert alert-danger" role="alert">
             @ViewData["NoCartItems"]
         </div>
     }
     <div style="margin-top: 5%;">
         <header class="text-left">
             <h6 class="display-4">@ViewData["PaidItems"]</h6>
         </header>
        @if (ViewBag.HasPaidForItems != null)
        {
             <div class="text-left">
                 <label class="display-6">User Has Paid Items</label>
             </div>
         }
         else
         {
             <div class="alert alert-danger" role="alert">
                User Does Not Have Paid Items
             </div>
         }
        </div>
        <div style="margin-top:5%;">
            <header class="text-left">
                <h6 class="display-4">@ViewData["ShoppingLists"]</h6>
            </header>
            @if (ViewBag.HasShoppingLists == null)
            {
                <div class="alert alert-danger" role="alert">
                    User Does Not Have Any Shopping Lists
                </div>
            }
            else
            {
                <div class="table-responsive-md" style="margin-top: 2%;">
                    <table class="table table-striped">
                       <thead>
                           <tr>
                               <th>List ID</th>
                               <th>List Name</th>
                           </tr>
                       </thead>
                       <tbody>
                       @foreach (var list in Model.shoppingLists)
                       {
                            <tr>
                                 <td>
                                     @Html.DisplayFor(modelItem => list.userListID)
                                 </td>
                                 <td>
                                     @Html.DisplayFor(modelItem => list.listName)
                                 </td>
                            </tr>
                        }
                        </tbody>
                    </table>
                </div>
            }
     </div>
     <div style="margin-top: 5%;">
         <header class="text-left">
             <h6 class="display-4">@ViewData["FavoriteItems"]</h6>
         </header>
         @if (ViewBag.HasFavorites != null)
         {
             <p>User Has Favorites</p>
         }
         else
         {
             <div class="alert alert-danger" role="alert">
                 User Does Not Have Favorites
             </div>
         }
     </div>
</div>

@await Html.PartialAsync("/Views/PartialViews/Spinner.cshtml")

Admin/Views/AdminUsers/Edit.cshtml
@model RnR.Admin.Entities.User

@{ ViewData["Title"] = "Edit User"; }

<div class="container" id="page__content" style="display:none;">
    <header class="text-center">
        <h4 class="display-4">@ViewData["Title"]</h4>
    </header>

    <div class="col-md-7 col-lg-12">
        <form class="form-vertical needs-validation" novalidate style="margin-top:6rem;" asp-controller="AdminUsers" asp-action="Edit" method="post" role="form">
            @Html.HiddenFor(model => model.encPassword)
            @Html.HiddenFor(model => model.doj)
            @Html.HiddenFor(model => model.userID)
            <div class="row g-3" style="margin-left: 25%;">
                <div class="col-sm-4" style="margin-top: 25px;">
                    <label asp-for="firstName" class="form-label" style="text-align:center">First Name</label>
                    <input type="text" class="form-control" asp-for="firstName" placeholder="" value="@Model.firstName" required />
                    <div class="invalid-feedback">
                        A valid first name is required
                    </div>
                </div>
                <div class="col-sm-4" style="margin-top: 25px;">
                    <label asp-for="lastName" class="form-label" style="text-align:center">Last Name</label>
                    <input type="text" class="form-control" asp-for="lastName" placeholder="" value="@Model.lastName" required />
                    <div class="invalid-feedback">
                        A valid last name is required
                    </div>
                </div>
            </div>
            <div class="row g-3" style="margin-left: 25%;">
                <div class="col-sm-4" style="margin-top: 25px;">
                    <label asp-for="email" class="form-label" style="text-align:center">Email Address</label>
                    <input type="email" class="form-control" asp-for="email" placeholder="" value="@Model.email" required />
                    <div class="invalid-feedback">
                        A valid email is required
                    </div>
                </div>
                <div class="col-sm-4" style="margin-top: 25px;">
                    <label asp-for="userRole" class="form-label" style="text-align:center">User Role</label>
                    <select class="form-control" asp-for="userRole" required>
                        <option value="">Select User Role...</option>
                        <option value="User">User</option>
                        <option value="Admin">Admin</option>
                    </select>
                    <div class="invalid-feedback">
                        A valid user role is required
                    </div>
                </div>
            </div>
            <div style="text-align:center;margin-top:3rem;padding-top:1rem;">
                <div class="container">
                    <div class="row">
                        <div class="col-md-12 col-sm-6">
                            <input class="btn btn-primary" type="submit" value="Update User" />
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

@await Html.PartialAsync("/Views/PartialViews/Spinner.cshtml")

Admin/Views/AdminUsers/Index.cshtml
@model X.PagedList.IPagedList<RnR.Admin.Entities.User>
@using X.PagedList.Mvc.Core;

@{
    ViewData["Title"] = "Users";
}

<div id="page__content" style="display:none;">
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-md-12">
                <header class="text-center">
                    <h4 class="display-4">@ViewData["Title"]</h4>
                </header>
            </div>
        </div>
    </div>
    <div class="container" style="margin-top: 25px;">
        <div class="row">
            <div class="col-6" style="float:left;">
                <p style="margin: 5px 0px;">
                    @Html.ActionLink("Create User", "Create")
                </p>
            </div>
            <div class="col-6" style="float:right;">
                @using (Html.BeginForm("Index", "AdminUsers", FormMethod.Get))
                {
                    <p style="margin: 5px 0px; float:right;">
                    @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
                    <input style="margin: 5px 0px;" type="submit" value="Search" />
                    </p>
                }
            </div>
        </div>
        <div class="row" style="margin-top: 10px;">
            <div class="col-xs-12 col-md-12">
                @if (ViewBag.NoUsersFound != null)
                {
                    <div id="warning__section" class="alert alert-danger" style="text-align:center; margin-top: 10%;">
                        <strong>@ViewBag.NoUsersFound</strong>
                    </div>
                }
                else
                {
                    <div class="table-responsive-md">
                        <table class="table table-striped">
                             <thead>
                                <tr>
                                    <th>@Html.ActionLink("Role", "Index", new { sortOrder = ViewBag.UserRoleSortParam, currentFilter = ViewBag.CurrentFilter })</th>
                                    <th>@Html.ActionLink("Name", "Index", new { sortOrder = ViewBag.NameSortParam, currentFilter = ViewBag.CurrentFilter })</th>
                                    <th>@Html.ActionLink("Surname", "Index", new { sortOrder = ViewBag.LastNameSortParam, currentFilter = ViewBag.CurrentFilter })</th>
                                    <th>@Html.ActionLink("Email", "Index", new { sortOrder = ViewBag.EmailSortParam, currentFilter = ViewBag.CurrentFilter })</th>
                                    <th>@Html.ActionLink("Date Joined", "Index", new { sortOrder = ViewBag.DateSortParam, currentFilter = ViewBag.CurrentFilter })</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var user in Model)
                                {
                                        <tr>
                                            <td>
                                                @Html.DisplayFor(modelItem => user.userRole)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => user.firstName)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => user.lastName)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => user.email)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => user.doj)
                                            </td>
                                            <td>
                                                @Html.ActionLink("Edit", "Edit", new { userID = user.userID, email = user.email }) |
                                                @Html.ActionLink("Details", "Details", new { userID = user.userID, email = user.email }) |
                                                @Html.ActionLink("Delete", "Delete", new { userID = user.userID, email = user.email })
                                            </td>
                                        </tr>
                                    }
                            </tbody>
                        </table>
                        <div class="container">
                            <div style="float:right;">
                                @Html.PagedListPager(Model, page => Url.Action("Index",
                                          new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }),
                                          new X.PagedList.Web.Common.PagedListRenderOptions
                                          {
                                              DisplayLinkToIndividualPages = true,
                                              LiElementClasses = new string[] { "page-item" },
                                              PageClasses = new string[] { "page-link" }
                                          })
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

@await Html.PartialAsync("/Views/PartialViews/Spinner.cshtml")